[tools]
fd = "latest"
lazygit = "latest"
luajit = "latest"
neovim = "latest"
node = "24"
python = "3.12"
ripgrep = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@github/copilot-language-server" = "latest"

[settings]
python_compile = false
idiomatic_version_file_enable_tools = ["node", "python"]
