[tools]
luajit = "latest"
neovim = "latest"
python = "3.12"
ripgrep = "latest"
"ubi:junegunn/fzf" = "latest"

[settings]
python_compile = false
idiomatic_version_file_enable_tools = ["node", "python"]
