luajit = "latest"
neovim = "latest"
node = "24"
python = "3.12"
"cargo:rep-grep" = "latest"
ripgrep = "latest"
"ubi:junegunn/fzf" = "latest"

[settings]
python_compile = false
idiomatic_version_file_enable_tools = ["node", "python"]
